# Generated by Django 6.0.5 on 2026-05-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('retail_price', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='api_fuelsta_state_4b82c5_idx'), models.Index(fields=['retail_price'], name='api_fuelsta_retail__926c06_idx'), models.Index(fields=['latitude', 'longitude'], name='api_fuelsta_latitud_a8079e_idx')],
            },
        ),
    ]
